const j = require('../data/content.json')
console.log('Keys:', Object.keys(j).join(', '))
if (j.noticias) console.log('Noticias count:', j.noticias.length)
if (j.eventos) console.log('Eventos count:', j.eventos.length)
if (j.calendario) console.log('Calendario count:', j.calendario.length)
if (j.documentos) console.log('Documentos count:', j.documentos.length)
if (j.config) console.log('Config key count:', Object.keys(j.config).length)
if (j.eventos && j.eventos.length > 0) console.log('Evento sample keys:', Object.keys(j.eventos[0]).join(', '))
if (j.noticias && j.noticias.length > 0) console.log('Noticia sample keys:', Object.keys(j.noticias[0]).join(', '))
